version: '3.7'
services:
  web-dev:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '127.0.0.1:3001:80'
    env_file: .env
    depends_on:
      - postgres
    restart: unless-stopped
    command: npm run start:dev

  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    env_file:
      - .postgres.env
    restart: unless-stopped
    volumes:
      - /data/rent-a-car/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
